[package]
name = "rid"
version = "0.1.0"
edition = "2021"
description = "rm"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.20", features = ["derive"] }
dirs = "5.0.1"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
